### ISSUE TITLE
三元组代码

### ISSUE THREAD

**Issue by zhangzhaoyuela** [percent4/knowledge_graph_demo#1]
您好，可以提供一下根据实体得到三元组的代码吗

**Comment by Asthestarfall** [comment]
create nodes successfully!
Traceback (most recent call last):
  File "D:\knowledge_graph_demo-master\knowledge_graph_demo-master\xlsx_2_neo4j.py", line 31, in <module>
    s_node = matcher.match("Node", name=S).first()
  File "D:\hhh\envs\pytorch\lib\site-packages\py2neo\matching.py", line 94, in first
    return self.graph.evaluate(*self._query_and_parameters())
  File "D:\hhh\envs\pytorch\lib\site-packages\py2neo\database.py", line 395, in evaluate
    return self.begin(autocommit=True).evaluate(cypher, parameters, **kwparameters)
  File "D:\hhh\envs\pytorch\lib\site-packages\py2neo\database.py", line 876, in evaluate
    return self.run(cypher, parameters, **kwparameters).evaluate(0)
  File "D:\hhh\envs\pytorch\lib\site-packages\py2neo\database.py", line 823, in run
    return Cursor(self.connector.run(statement=cypher,
  File "D:\hhh\envs\pytorch\lib\site-packages\py2neo\internal\connectors.py", line 292, in run
    return self._run_1(statement, parameters, graph, keys, entities)
  File "D:\hhh\envs\pytorch\lib\site-packages\py2neo\internal\connectors.py", line 255, in _run_1
    cx.fetch()
  File "D:\hhh\envs\pytorch\lib\site-packages\neobolt\direct.py", line 419, in fetch
    return self._fetch()
  File "D:\hhh\envs\pytorch\lib\site-packages\neobolt\direct.py", line 461, in _fetch
    response.on_failure(summary_metadata or {})
  File "D:\hhh\envs\pytorch\lib\site-packages\neobolt\direct.py", line 751, in on_failure
    handler(metadata)
  File "D:\hhh\envs\pytorch\lib\site-packages\py2neo\internal\connectors.py", line 288, in _fail
    raise GraphError.hydrate(metadata)
py2neo.database.ClientError: SyntaxError: Invalid input '{': expected "+" or "-" (line 1, column 31 (offset: 30))
"MATCH (_:Node) WHERE _.name = {1} RETURN _"
                               ^

**Comment by Asthestarfall** [comment]
What's wrong with this error report? Thanks
